// Generated by https://quicktype.io

import { User } from "../../domain/entities/user";

export interface AuthResponse {
    id: string;
    email: string;
    fullName: string;
    isActive: boolean;
    roles: string[];
    token: string;
}

export interface UserToken { 
    user: User;
    token: string;
}

export interface ErrorResponse { 
    message: string;
    error: string;
    statusCode: number;
}