export enum ActionCamera {
    TAKE_PICTURE = 'TAKE_PICTURE',
    PICK_IMAGE = 'PICK_IMAGE',
    PICK_VIDEO = 'PICK_VIDEO',
    PICK_FILE = 'PICK_FILE',
    PICK_MULTIPLE_FILES = 'PICK_MULTIPLE_FILES',
    PICK_MULTIPLE_IMAGES = 'PICK_MULTIPLE_IMAGES',
    PICK_MULTIPLE_VIDEOS = 'PICK_MULTIPLE_VIDEOS',
    PICK_MULTIPLE_MEDIAS = 'PICK_MULTIPLE_MEDIAS',
}