// Generated by https://quicktype.io

import { User } from "../../../domain/entities/user";

export interface ProductListResponse {
    id: string;
    title: string;
    price: number;
    description: string;
    slug: string;
    stock: number;
    sizes: Size[];
    gender: Gender;
    tags: Tag[];
    images: string[];
    user: User;
}

export enum Size {
    S = "S",
    M = "M",
    L = "L",
    Xs = "XS",
    Xl = "XL",
    Xxl = "XXL",
}

export enum Tag {
    Hats = "hats",
    Hoodie = "hoodie",
    Shirt = "shirt",
}

export enum Gender {
    Kid = 'kid',
    Men = 'men',
    Women = 'women',
    Unisex = 'unisex'
}