// Generated by https://quicktype.io

import { User } from "../../../domain/entities/user";

export interface ProductListResponse {
    id:          string;
    title:       string;
    price:       number;
    description: string;
    slug:        string;
    stock:       number;
    sizes:       Size[];
    gender:      string;
    tags:        Tag[];
    images:      string[];
    user:        User;
}

export enum Size {
    L = "L",
    M = "M",
    S = "S",
    Xl = "XL",
    Xs = "XS",
    Xxl = "XXL",
}

export enum Tag {
    Hats = "hats",
    Hoodie = "hoodie",
    Shirt = "shirt",
}

